[package]
name = "svc-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
thiserror = "2.0"
pulldown-cmark = "0.13"
tempfile = "3.23.0"

